### ISSUE TITLE
Why not just use Jython?

### ISSUE THREAD

**Issue by djoffrey** [mzheravin/openpredict#1]
Hi, thanks for your *AMAZING* project.

But this project is a little lack of docs. 

BTW, did you consider supporting Jython to be the strategy language instead of DSL using ANTLR?

**Comment by mzheravin** [comment]
Hi! 

First of all, thanks for your interest to my project! 
You absolutely right, there is no documentation - I definitely need to start with adding some description.

Basically there are two ideas I was trying implemented for back-testing:
1. First is a regular algorithmic trading using asynchronous API (implementing EventStrategy). This gives performance about 300-600 million events (price changes) per second with a regular server machine.  The most efficient is to use java for strategy implementation, but technically you can attach any language.
2. Second is more specific approach. It is applicable only for indicator-guided market making strategies (implementing FasMMStrategy). Big advantage here is that you can pre-process a lot of things and re-use them through back testing. In addition significant part of calculations can be transferred to a GPU (I was doing some experiments with jCuda and it looks very promising). This pre-processing stage is quite similar to how TensorFlow operates with its data regarding to representation and optimizations. But even with CPU it is 10+ times faster than back-testing based on event processing. With such high performance of back-testing you can generate new indicator formulas instead of just being limited by trying different parameters for a single strategy. This is why I have developed special language, formula generation module, and ANTLR-based parser for it so that he formula can be read by human, stored, loaded as a DAG and processed very efficient way. I don't think using Jython would add much value, unless you going to automatically generate some algorithms (not just indicator processing formulas). But in my opinion it does not make much sense considering O(m * r^k * n!) complexity, where m - size of historical data,  n - size of the strategy, and k is number of parameters and r is a number of possible values.

**Comment by djoffrey** [comment]
> Hi!
> 
> First of all, thanks for your interest to my project!
> You absolutely right, there is no documentation - I definitely need to start with adding some description.
> 
> Basically there are two ideas I was trying implemented for back-testing:
> 
> 1. First is a regular algorithmic trading using asynchronous API (implementing EventStrategy). This gives performance about 300-600 million events (price changes) per second with a regular server machine.  The most efficient is to use java for strategy implementation, but technically you can attach any language.
> 2. Second is more specific approach. It is applicable only for indicator-guided market making strategies (implementing FasMMStrategy). Big advantage here is that you can pre-process a lot of things and re-use them through back testing. In addition significant part of calculations can be transferred to a GPU (I was doing some experiments with jCuda and it looks very promising). This pre-processing stage is quite similar to how TensorFlow operates with its data regarding to representation and optimizations. But even with CPU it is 10+ times faster than back-testing based on event processing. With such high performance of back-testing you can generate new indicator formulas instead of just being limited by trying different parameters for a single strategy. This is why I have developed special language, formula generation module, and ANTLR-based parser for it so that he formula can be read by human, stored, loaded as a DAG and processed very efficient way. I don't think using Jython would add much value, unless you going to automatically generate some algorithms (not just indicator processing formulas). But in my opinion it does not make much sense considering O(m * r^k * n!) complexity, where m - size of historical data,  n - size of the strategy, and k is number of parameters and r is a number of possible values.

Well. First, thanks for such an informative reply.
1. Jython is based on JVM, and being able to interplote with JAVA runtime, it's just basicly a syntax layer, and the python lang is more a little more human readable, and data scientists and traders love it.(Of cause I heard JAVA works well too).

2. Well, if you mean using GPU is much faster than CPU, of cause, but I think what valuable is the algorithm you transform those heavy calculation operation stage into GPU-compatible code. 

BTW, I don't mean to make some debate of 'What language is better', just a little advice in DSL choosing. And good project, thanks for sharing. Are you going to update it again?

**Comment by djoffrey** [comment]
Closed
